import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {FaGithubAlt,FaLinkedinIn,FaFigma} from 'react-icons/fa'
import About from './about'
import Projects from './projects'
import { motion,AnimatePresence } from 'framer-motion'
import myPic from '../images/picnisha.png'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <motion.div nitial={{ y: "100%" }} animate={{ y: "calc(65vw - 100%)"}} transition={{duration:2}} className={styles.iconsContainer}>
          <a href="https://github.com/NishaSaraswat07" target="_blank"><FaGithubAlt /></a>
          <a href="https://www.linkedin.com/in/nishasaraswat/" target="_blank"><FaLinkedinIn /></a>
          <a href="https://www.figma.com/files/recent?fuid=933343078711531768" target="_blank"><FaFigma /></a>
          <div className={styles.vl}></div>
          </motion.div>
            <motion.div className={styles.center} initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{
                duration: 1,
                delay: 1,
                ease: [0, 0.71, 0.2, 1.01]
              }}>
              <Image src={myPic} alt = 'my pic' width={260} height={260} priority/>
              <motion.h2 initial={{ x: "100%" }}
                animate={{ x: "calc(30vw - 100%)" }} transition={{duration:3}}>Nisha</motion.h2>
              <motion.p>I am a frontend developer</motion.p>
            </motion.div>
      </main>
      <div>
        <About />
      </div>
      <div>
        <Projects/>
      </div>
    </>
  )
}
